### ISSUE TITLE
Confusing Behavior of Active Shirley Background

### ISSUE THREAD

**Issue by strategos-nzr** [Julian-Hochhaus/lmfitxps#12]
Hello,

In the code for the activate shirley background model calculation there is the term:

```python
 # Next ensure the energy values are *decreasing* in the array,
    # if not, reverse them.
    if x[0] < x[-1]:
        is_reversed = True
        x = x[::-1]
        y = y[::-1]
    else:
        is_reversed = False
```
Since arrays in numpy (python) are mutable, and are shallow copies, this can mutate the original data set of binding energies and intensities, and result in some odd behavior.

This has left me rather bewildered in an attempt to curve fit a certain compound with a doniach dublett.
The shirley background here thus has a 'strange' interaction with Doniach-Sunjic lineshapes, which, as implemented in `lmfit` produce a nonsymmetrical peak shape which has a tail along the 'decreasing x' direction.

I solved this by going from binding energy to an arbitrary kinetic energy. The behavior is definitely unexpected, however.
perhaps `deepcopy` can be used instead?

![image](https://github.com/user-attachments/assets/df56641e-fde5-4b23-b7d8-89b60b4d406b)

**Comment by Julian-Hochhaus** [comment]
Great catch, thanks!

**Comment by Julian-Hochhaus** [comment]
Hey @strategos-nzr,

I just pushed a fix that should (hopefully!) solve the issue you were having. You can check it out in the newest [Release](https://pypi.org/project/lmfitxps/2.4.3/) or in this commit [#9dd84f6](https://github.com/Julian-Hochhaus/lmfitxps/commit/9dd84f6fd7ac9bd9a499664f3137683835c109c8)

When you get a chance, could you give it a try and let me know if it works for you? If anything's still off, feel free to ping me!

Thanks!

Julian
